spring:
  application:
    name: notificacao

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/notificacao-db}

  cloud:
    function:
      definition: notificacoes
    stream:
      kafka:
        binder:
          brokers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      bindings:
        notificacoes-in-0:
          destination: transacoes-aprovadas,transacoes-reprovadas
          group: notificacao-group
          consumer:
            auto-offset-reset: earliest

server:
  port: 8083

logging:
  level:
    com.banking.notificacao: INFO
    org.springframework.cloud.stream: DEBUG

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      newrelic:
        enabled: false