spring:
  application:
    name: transacao
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/transacao-db

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notificacao-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8082

saldo:
  service:
    url: http://localhost:8081

camunda:
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest
      worker-id: transacao-worker
      max-tasks: 10
      lock-duration: 10000

logging:
  level:
    com.banking.transacao: INFO
    org.springframework.kafka: DEBUG